-- Generated by supabase/seed-data/build-seed-sql.mjs
-- Review before applying. This file intentionally covers games and venues only.
-- Inventory should continue to come from Scout Mode reports and approvals.
-- Missing venue coordinates can be auto-geocoded through the Supabase geocode
-- Edge Function when EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_KEY are
-- available in the local environment or the project .env file.

begin;

insert into public.games (slug, title, manufacturer, release_year, aliases)
values
  (
    'street-fighter-ii-champion-edition',
    'Street Fighter II'': Champion Edition',
    'Capcom',
    1992,
    array['Champion Edition', 'SF2 CE', 'Street Fighter 2 Champion Edition']
  ),
  (
    'super-street-fighter-ii-turbo',
    'Super Street Fighter II Turbo',
    'Capcom',
    1994,
    array['ST', 'Super Turbo', 'SSF2T']
  ),
  (
    'street-fighter-alpha-2',
    'Street Fighter Alpha 2',
    'Capcom',
    1996,
    array['SFA2', 'Alpha 2']
  ),
  (
    'street-fighter-alpha-3',
    'Street Fighter Alpha 3',
    'Capcom',
    1998,
    array['SFA3', 'Alpha 3']
  ),
  (
    'street-fighter-iii-3rd-strike',
    'Street Fighter III: 3rd Strike',
    'Capcom',
    1999,
    array['3rd Strike', 'Third Strike', 'SF3S', 'SFIII 3S']
  ),
  (
    'street-fighter-iv-arcade-edition',
    'Super Street Fighter IV Arcade Edition',
    'Capcom',
    2010,
    array['SF4 AE', 'Arcade Edition', 'SSF4 AE']
  ),
  (
    'street-fighter-v-type-arcade',
    'Street Fighter V: Type Arcade',
    'Capcom',
    2019,
    array['SFV Type Arcade', 'Street Fighter V Arcade']
  ),
  (
    'tekken-3',
    'Tekken 3',
    'Namco',
    1997,
    array['Tekken III']
  ),
  (
    'tekken-tag-tournament',
    'Tekken Tag Tournament',
    'Namco',
    1999,
    array['TTT', 'Tekken Tag']
  ),
  (
    'tekken-5-dark-resurrection',
    'Tekken 5: Dark Resurrection',
    'Namco',
    2005,
    array['T5DR', 'Dark Resurrection']
  ),
  (
    'tekken-7-fated-retribution',
    'TEKKEN 7: Fated Retribution',
    'Bandai Namco',
    2016,
    array['Tekken 7 FR', 'T7FR', 'Tekken 7']
  ),
  (
    'soulcalibur',
    'Soulcalibur',
    'Namco',
    1998,
    array['Soul Calibur', 'SC1']
  ),
  (
    'soulcalibur-ii',
    'Soulcalibur II',
    'Namco',
    2002,
    array['Soul Calibur 2', 'SC2']
  ),
  (
    'virtua-fighter-5-final-showdown',
    'Virtua Fighter 5 Final Showdown',
    'Sega',
    2010,
    array['VF5FS', 'Virtua Fighter 5 FS']
  ),
  (
    'marvel-super-heroes-vs-street-fighter',
    'Marvel Super Heroes vs. Street Fighter',
    'Capcom',
    1997,
    array['MSHvSF', 'Marvel vs Street Fighter']
  ),
  (
    'marvel-vs-capcom-clash-of-super-heroes',
    'Marvel vs. Capcom: Clash of Super Heroes',
    'Capcom',
    1998,
    array['MVC1', 'Marvel vs Capcom 1']
  ),
  (
    'marvel-vs-capcom-2',
    'Marvel vs. Capcom 2',
    'Capcom',
    2000,
    array['MVC2', 'Marvel 2', 'Marvel vs Capcom 2']
  ),
  (
    'x-men-vs-street-fighter',
    'X-Men vs. Street Fighter',
    'Capcom',
    1996,
    array['XvSF', 'X-Men vs SF']
  ),
  (
    'capcom-vs-snk-2',
    'Capcom vs. SNK 2',
    'Capcom',
    2001,
    array['CvS2', 'Capcom vs SNK 2']
  ),
  (
    'melty-blood-actress-again-current-code',
    'Melty Blood Actress Again Current Code',
    'Ecole Software',
    2010,
    array['MBAACC', 'Melty Blood']
  ),
  (
    'guilty-gear-xx-accent-core-plus-r',
    'Guilty Gear XX Accent Core Plus R',
    'Arc System Works',
    2012,
    array['AC+R', 'Accent Core Plus R']
  ),
  (
    'guilty-gear-xrd-rev-2',
    'Guilty Gear Xrd REV 2',
    'Arc System Works',
    2017,
    array['Rev 2', 'Xrd Rev 2', 'GGXrd']
  ),
  (
    'blazblue-centralfiction',
    'BlazBlue Centralfiction',
    'Arc System Works',
    2015,
    array['BBCF', 'Centralfiction']
  ),
  (
    'the-king-of-fighters-98',
    'The King of Fighters ''98',
    'SNK',
    1998,
    array['KOF 98', 'KoF98']
  ),
  (
    'the-king-of-fighters-2002-unlimited-match',
    'The King of Fighters 2002 Unlimited Match',
    'SNK',
    2009,
    array['KOF 2002 UM', 'KoF 2002 UM']
  ),
  (
    'garou-mark-of-the-wolves',
    'Garou: Mark of the Wolves',
    'SNK',
    1999,
    array['Garou', 'MOTW', 'Mark of the Wolves']
  ),
  (
    'samurai-shodown-v-special',
    'Samurai Shodown V Special',
    'SNK',
    2004,
    array['SamSho V Special', 'SS5SP']
  ),
  (
    'killer-instinct',
    'Killer Instinct',
    'Midway',
    1994,
    array['KI1', 'Killer Instinct 1']
  ),
  (
    'killer-instinct-2',
    'Killer Instinct 2',
    'Midway',
    1996,
    array['KI2']
  ),
  (
    'mortal-kombat-ii',
    'Mortal Kombat II',
    'Midway',
    1993,
    array['MK2', 'Mortal Kombat 2']
  ),
  (
    'ultimate-mortal-kombat-3',
    'Ultimate Mortal Kombat 3',
    'Midway',
    1995,
    array['UMK3']
  ),
  (
    'mortal-kombat-4',
    'Mortal Kombat 4',
    'Midway',
    1997,
    array['MK4']
  ),
  (
    'dance-dance-revolution-extreme',
    'DanceDanceRevolution Extreme',
    'Konami',
    2002,
    array['DDR Extreme', 'Extreme']
  ),
  (
    'dance-dance-revolution-supernova',
    'DanceDanceRevolution SuperNOVA',
    'Konami',
    2006,
    array['DDR SuperNOVA', 'Supernova']
  ),
  (
    'dance-dance-revolution-a20',
    'DanceDanceRevolution A20',
    'Konami',
    2019,
    array['DDR A20', 'DDRA20', 'A20']
  ),
  (
    'dance-dance-revolution-a20-plus',
    'DanceDanceRevolution A20 Plus',
    'Konami',
    2020,
    array['DDR A20 Plus', 'DDR A20+', 'DDRA20+', 'A20 Plus']
  ),
  (
    'pump-it-up-prime-2',
    'Pump It Up PRIME 2',
    'Andamiro',
    2017,
    array['PIU Prime 2', 'Pump Prime 2']
  ),
  (
    'pump-it-up-phoenix',
    'Pump It Up PHOENIX',
    'Andamiro',
    2023,
    array['PIU Phoenix', 'Pump Phoenix']
  ),
  (
    'sound-voltex-exceed-gear',
    'SOUND VOLTEX EXCEED GEAR',
    'Konami',
    2021,
    array['SDVX', 'Sound Voltex', 'Exceed Gear']
  ),
  (
    'beatmania-iidx-31-epolis',
    'beatmania IIDX 31 EPOLIS',
    'Konami',
    2023,
    array['IIDX 31', 'EPOLIS', 'beatmania IIDX']
  ),
  (
    'gitadora-fuzz-up',
    'GITADORA FUZZ-UP',
    'Konami',
    2022,
    array['GITADORA', 'Drummania', 'GuitarFreaks']
  ),
  (
    'jubeat-festo',
    'jubeat festo',
    'Konami',
    2018,
    array['Jubeat']
  ),
  (
    'taiko-no-tatsujin-green-version',
    'Taiko no Tatsujin Green Version',
    'Bandai Namco',
    2019,
    array['Taiko', 'Taiko no Tatsujin']
  ),
  (
    'maimai-finale',
    'maimai FiNALE',
    'Sega',
    2018,
    array['maimai']
  ),
  (
    'house-of-the-dead-2',
    'The House of the Dead 2',
    'Sega',
    1998,
    array['HOTD2', 'House of the Dead 2']
  ),
  (
    'house-of-the-dead-4',
    'The House of the Dead 4',
    'Sega',
    2005,
    array['HOTD4', 'House of the Dead 4']
  ),
  (
    'time-crisis-2',
    'Time Crisis 2',
    'Namco',
    1997,
    array['TC2', 'Time Crisis II']
  ),
  (
    'time-crisis-3',
    'Time Crisis 3',
    'Namco',
    2002,
    array['TC3', 'Time Crisis III']
  ),
  (
    'time-crisis-4',
    'Time Crisis 4',
    'Namco',
    2006,
    array['TC4', 'Time Crisis IV']
  ),
  (
    'luigis-mansion-arcade',
    'Luigi''s Mansion Arcade',
    'Capcom',
    2015,
    array['Luigis Mansion Arcade', 'Luigi Arcade']
  ),
  (
    'halo-fireteam-raven',
    'Halo: Fireteam Raven',
    'Raw Thrills',
    2018,
    array['Fireteam Raven', 'Halo Arcade']
  ),
  (
    'jurassic-park-arcade',
    'Jurassic Park Arcade',
    'Raw Thrills',
    2015,
    array['Jurassic Park Raw Thrills', 'Jurassic Park']
  ),
  (
    'terminator-salvation',
    'Terminator Salvation',
    'Raw Thrills',
    2009,
    array['Terminator Salvation Arcade']
  ),
  (
    'point-blank-2',
    'Point Blank 2',
    'Namco',
    1999,
    array['Gun Bullet 2', 'Point Blank II']
  ),
  (
    'daytona-usa',
    'Daytona USA',
    'Sega',
    1994,
    array['Daytona']
  ),
  (
    'daytona-usa-2',
    'Daytona USA 2',
    'Sega',
    1998,
    array['Daytona 2']
  ),
  (
    'initial-d-arcade-stage-8-infinity',
    'Initial D Arcade Stage 8 Infinity',
    'Sega',
    2014,
    array['Initial D 8', 'ID8', 'IDAS8', 'Initial D Infinity']
  ),
  (
    'initial-d-the-arcade',
    'Initial D THE ARCADE',
    'Sega',
    2021,
    array['IDAC', 'Initial D Arcade']
  ),
  (
    'outrun-2-sp',
    'OutRun 2 SP',
    'Sega',
    2004,
    array['OutRun 2 SP', 'Outrun 2']
  ),
  (
    'mario-kart-arcade-gp-dx',
    'Mario Kart Arcade GP DX',
    'Bandai Namco',
    2013,
    array['MKAGPDX', 'Mario Kart Arcade']
  ),
  (
    'cruisn-blast',
    'Cruis''n Blast',
    'Raw Thrills',
    2017,
    array['Cruisn Blast', 'Cruisin Blast']
  ),
  (
    'fast-and-furious-arcade',
    'Fast & Furious Arcade',
    'Raw Thrills',
    2022,
    array['Fast and Furious Arcade', 'FNF Arcade']
  ),
  (
    'the-simpsons',
    'The Simpsons',
    'Konami',
    1991,
    array['Simpsons Arcade']
  ),
  (
    'teenage-mutant-ninja-turtles-turtles-in-time',
    'Teenage Mutant Ninja Turtles: Turtles in Time',
    'Konami',
    1991,
    array['TMNT Turtles in Time', 'Turtles in Time']
  ),
  (
    'x-men',
    'X-Men',
    'Konami',
    1992,
    array['X-Men Arcade']
  ),
  (
    'aliens-vs-predator',
    'Aliens vs. Predator',
    'Capcom',
    1994,
    array['AVP', 'Aliens vs Predator']
  ),
  (
    'metal-slug-3',
    'Metal Slug 3',
    'SNK',
    2000,
    array['MS3', 'Metal Slug III']
  ),
  (
    'metal-slug-x',
    'Metal Slug X',
    'SNK',
    1999,
    array['MSX', 'Metal Slug X']
  ),
  (
    'nba-jam',
    'NBA Jam',
    'Midway',
    1993,
    array['NBA Jam Tournament Edition', 'NBA Jam TE']
  ),
  (
    'killer-queen',
    'Killer Queen',
    'BumbleBear Games',
    2013,
    array['KQ', 'Killer Queen Arcade']
  ),
  (
    'pac-man-battle-royale',
    'Pac-Man Battle Royale',
    'Namco',
    2011,
    array['Pac Man Battle Royale', 'PMBR']
  ),
  (
    'galaga-assault',
    'Galaga Assault',
    'Namco',
    2008,
    array['Galaga Assault Arcade']
  ),
  (
    'ms-pac-man',
    'Ms. Pac-Man',
    'Midway',
    1982,
    array['Ms Pac Man', 'Miss Pac Man']
  ),
  (
    'galaga',
    'Galaga',
    'Namco',
    1981,
    array['Galaga ''81']
  ),
  (
    'donkey-kong',
    'Donkey Kong',
    'Nintendo',
    1981,
    array['DK', 'Donkey Kong Arcade']
  ),
  (
    'centipede',
    'Centipede',
    'Atari',
    1981,
    array['Centipede Arcade']
  ),
  (
    'asteroids',
    'Asteroids',
    'Atari',
    1979,
    array['Asteroids Arcade']
  )
on conflict (slug) do update
set
  title = excluded.title,
  manufacturer = excluded.manufacturer,
  release_year = excluded.release_year,
  aliases = excluded.aliases;

insert into public.venues (
  slug,
  name,
  street_address,
  city,
  region,
  postal_code,
  country,
  source,
  status,
  location,
  metadata
)
values
  (
    'cidercade-dallas',
    'Cidercade Dallas',
    '2777 Irving Blvd',
    'Dallas',
    'TX',
    '75207',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-96.846625, 32.805817),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://cidercade.com/dallas/', 'notes', 'Official site says nearly 200 games and original Dallas location.')
  ),
  (
    'cidercade-arlington',
    'Cidercade Arlington',
    '500 E. Division St.',
    'Arlington',
    'TX',
    '76011',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.102525, 32.738199),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://cidercade.com/arlington/', 'notes', 'Official site says 275+ games and strong central-Arlington destination traffic.')
  ),
  (
    'cidercade-fort-worth',
    'Cidercade Fort Worth',
    '1813 West Bowie St.',
    'Fort Worth',
    'TX',
    '76110',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.347171, 32.70741),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://cidercade.com/fortworth/', 'notes', 'Official site says 275+ games plus claw/ticket expansion.')
  ),
  (
    'free-play-richardson',
    'Free Play Richardson',
    '1730 E Belt Line Rd',
    'Richardson',
    'TX',
    '75081',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-96.693302, 32.943835),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://freeplayinc.com/richardson/', 'notes', 'Official site says 95+ arcade and pinball machines; heavily awarded DFW location.')
  ),
  (
    'free-play-dallas',
    'Free Play Dallas',
    '3015 Gulden Lane',
    'Dallas',
    'TX',
    '75212',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-96.828156, 32.779934),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://freeplayinc.com/dallas', 'notes', 'Official site says 160+ arcade games and pinball in Trinity Groves.')
  ),
  (
    'free-play-arlington',
    'Free Play Arlington',
    '400 E. South Street',
    'Arlington',
    'TX',
    '76010',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.103137, 32.734429),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://freeplayinc.com/arlington/', 'notes', 'Official site says 130+ retro arcade games and pinball.')
  ),
  (
    'free-play-fort-worth',
    'Free Play Fort Worth',
    '1311 Lipscomb St',
    'Fort Worth',
    'TX',
    '76104',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.3331, 32.730131),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://freeplayinc.com/fortworth/', 'notes', 'Official site says 90+ retro arcade games and pinball.')
  ),
  (
    'free-play-denton',
    'Free Play Denton',
    '101 W. Hickory Street',
    'Denton',
    'TX',
    '76201',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.132662, 33.214315),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://freeplayinc.com/denton/', 'notes', 'Official site says 120+ arcade games and pinball; important North Texas anchor.')
  ),
  (
    'round1-grapevine-mills',
    'Round1 Grapevine Mills',
    '3000 Grapevine Mills Pkwy',
    'Grapevine',
    'TX',
    '76051',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.04241, 32.96617),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://www.round1usa.com/locations/grapevine-mills', 'notes', 'Major mainstream DFW import/rhythm and crane destination.')
  ),
  (
    'round1-arlington-parks',
    'Round1 Arlington Parks',
    '3811 S Cooper St',
    'Arlington',
    'TX',
    '76015',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.129592, 32.679339),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://www.round1usa.com/locations/arlington-parks', 'notes', 'Large mainstream arcade destination with strong mall traffic.')
  ),
  (
    'nickel-mania-carrollton',
    'Nickel Mania Carrollton',
    '2661 Midway Rd. Suite 218',
    'Carrollton',
    'TX',
    '75006',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-96.844003, 32.986717),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://www.nickelmania.com/', 'notes', 'Official site says 100+ latest and classic video games with low-cost admission.')
  ),
  (
    'arcade-92-mckinney',
    'Arcade 92 McKinney',
    '305 E. Virginia St., Suite 103',
    'McKinney',
    'TX',
    '75069',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-96.612758, 33.198143),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://www.arcade92.com/mckinney', 'notes', 'Official site says 100+ free-play arcades in Historic Downtown McKinney.')
  ),
  (
    'arcade-92-flower-mound',
    'Arcade 92 Flower Mound',
    '801 International Parkway, Suite 580',
    'Flower Mound',
    'TX',
    '75022',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.063241, 32.991366),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://www.arcade92.com/flowermound', 'notes', 'Official site says 100+ free-play arcades; good North DFW candidate.')
  ),
  (
    'electric-starship-arcade',
    'Electric Starship Arcade',
    '5620 Denton Hwy',
    'Haltom City',
    'TX',
    '76148',
    'US',
    'seed',
    'active',
    extensions.st_setsrid(
      extensions.st_makepoint(-97.263281, 32.848805),
      4326
    )::extensions.geography,
    jsonb_build_object('website', 'https://electricstarshiparcade.com/', 'notes', 'Official site says 130-140 games on the floor and 200 in rotation.')
  )
on conflict (slug) do update
set
  name = excluded.name,
  street_address = excluded.street_address,
  city = excluded.city,
  region = excluded.region,
  postal_code = excluded.postal_code,
  country = excluded.country,
  source = excluded.source,
  status = excluded.status,
  location = excluded.location,
  metadata = excluded.metadata;

commit;
