-- Generated by scripts/build-mame-game-seed.mjs
-- Source: mame.xml
-- Games: 69
-- This file inserts/updates public.games only. It does not create venue inventory.

begin;

insert into public.games as g (
  slug,
  title,
  manufacturer,
  release_year,
  aliases,
  categories,
  external_ids,
  metadata
)
values
  (
    'yu-ka',
    'Yu-Ka',
    'Yubis / T.System',
    1999,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["yuka"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["seta/macs.cpp"]}'::jsonb
  ),
  (
    'yuanyang-hudie-meng',
    'Yuanyang Hudie Meng',
    'GMS',
    2005,
    array['Yuanyang Hudie Meng (Version 8.8A 2005-09-25)'],
    array['Arcade'],
    '{"mame":["yyhm"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/gms.cpp"]}'::jsonb
  ),
  (
    'yukon',
    'Yukon',
    'Exidy',
    1989,
    array['Yukon (version 2.0)'],
    array['Arcade'],
    '{"mame":["yukon"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["exidy/exidy440.cpp"]}'::jsonb
  ),
  (
    'yukon-gold',
    'Yukon Gold',
    'WMS',
    2000,
    array['Yukon Gold (Russian)'],
    array['Arcade'],
    '{"mame":["yukongld"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/wms.cpp"]}'::jsonb
  ),
  (
    'yumefuda',
    'Yumefuda',
    'Alba',
    1991,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["yumefuda"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["seta/albazg.cpp"]}'::jsonb
  ),
  (
    'z-100',
    'Z-100',
    'Zenith Data Systems',
    1982,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["z100"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["heathzenith/z100.cpp"]}'::jsonb
  ),
  (
    'z1013-matrix-8x4',
    'Z1013 (matrix 8x4)',
    'VEB Robotron Electronics Riesa',
    1985,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["z1013"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["robotron/z1013.cpp"]}'::jsonb
  ),
  (
    'z3-guitar-synthesizer',
    'Z3 Guitar Synthesizer',
    'Korg',
    1988,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["korgz3"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["korg/korgz3.cpp"]}'::jsonb
  ),
  (
    'z80-based-triple-time-zone-clock',
    'Z80 based, triple time zone clock',
    'Tom Storey',
    2020,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["z80clock"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["homebrew/z80clock.cpp"]}'::jsonb
  ),
  (
    'z80-dev-board',
    'Z80 dev board',
    '<unknown>',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["z80dev"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["homebrew/z80dev.cpp"]}'::jsonb
  ),
  (
    'z80ne',
    'Z80NE',
    'Nuova Elettronica',
    1980,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["z80ne"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/z80ne.cpp"]}'::jsonb
  ),
  (
    'z9001-kc-85-1-10',
    'Z9001 (KC 85/1.10)',
    'Robotron',
    1984,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["z9001"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["robotron/z9001.cpp"]}'::jsonb
  ),
  (
    'zarya-vostoka',
    'Zarya Vostoka',
    'Nova Games of Canada',
    1984,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zaryavos"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["taito/roundup.cpp"]}'::jsonb
  ),
  (
    'zaviga',
    'Zaviga',
    'Data East Corporation',
    1984,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zaviga"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["dataeast/bwing.cpp"]}'::jsonb
  ),
  (
    'zaxxon',
    'Zaxxon',
    'Sega',
    1982,
    array['Zaxxon (set 1, rev D)'],
    array['Arcade'],
    '{"mame":["zaxxon"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/zaxxon.cpp"]}'::jsonb
  ),
  (
    'zdog-44-in-1',
    'ZDog (44 in 1)',
    'Hummer Technology Co., Ltd.',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zdog"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["nintendo/nes_vt02_vt03.cpp"]}'::jsonb
  ),
  (
    'zed-blade-operation-ragnarok',
    'Zed Blade / Operation Ragnarok',
    'NMK',
    1994,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zedblade"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["neogeo/neogeo.cpp"]}'::jsonb
  ),
  (
    'zektor',
    'Zektor',
    'Sega',
    1982,
    array['Zektor (revision B)'],
    array['Arcade'],
    '{"mame":["zektor"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/segag80v.cpp"]}'::jsonb
  ),
  (
    'zelos',
    'Zelos',
    'Namco',
    1994,
    array['Zelos (Japan, main unit)', 'Zelos (Japan, terminal)'],
    array['Arcade'],
    '{"mame":["zelos","zelost"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["namco/namcona1.cpp"]}'::jsonb
  ),
  (
    'zen-nippon-pro-wres-featuring-virtua-j-971123-v1-000',
    'Zen Nippon Pro-Wres Featuring Virtua (J 971123 V1.000)',
    'Sega',
    1997,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["znpwfv"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/stv.cpp"]}'::jsonb
  ),
  (
    'zenigata-ponta',
    'Zenigata Ponta',
    'Amuzy Corporation',
    2005,
    array['Zenigata Ponta (Japan, ver 1.02)'],
    array['Arcade'],
    '{"mame":["zenponta"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/amuzy.cpp"]}'::jsonb
  ),
  (
    'zenkoku-seifuku-bishoujo-grand-prix-find-love-j-971212-v1-000',
    'Zenkoku Seifuku Bishoujo Grand Prix Find Love (J 971212 V1.000)',
    'Daiki / FCF',
    1997,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["findlove"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/stv.cpp"]}'::jsonb
  ),
  (
    'zero-konami-endeavour',
    'Zero (Konami Endeavour)',
    'Konami',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["konzero"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["konami/konendev.cpp"]}'::jsonb
  ),
  (
    'zero-gunner-export-model-2b',
    'Zero Gunner (Export, Model 2B)',
    'Psikyo',
    1997,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zerogun"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/model2.cpp"]}'::jsonb
  ),
  (
    'zero-gunner-2',
    'Zero Gunner 2',
    'Psikyo',
    2001,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zerogu2"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/naomi.cpp"]}'::jsonb
  ),
  (
    'zero-hour',
    'Zero Hour',
    'Universal',
    1980,
    array['Zero Hour (set 1)'],
    array['Arcade'],
    '{"mame":["zerohour"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["universal/zerohour.cpp"]}'::jsonb
  ),
  (
    'zero-point',
    'Zero Point',
    'Unico',
    1998,
    array['Zero Point (set 1)'],
    array['Arcade'],
    '{"mame":["zeropnt"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["unico/unico.cpp"]}'::jsonb
  ),
  (
    'zero-point-2',
    'Zero Point 2',
    'Unico',
    1999,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zeropnt2"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["unico/unico.cpp"]}'::jsonb
  ),
  (
    'zero-target',
    'Zero Target',
    'Data East Corporation',
    1985,
    array['Zero Target (World, CW)'],
    array['Arcade'],
    '{"mame":["zerotrgt"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["dataeast/cntsteer.cpp"]}'::jsonb
  ),
  (
    'zero-team-usa',
    'Zero Team USA',
    'Seibu Kaihatsu (Fabtek license)',
    1993,
    array['Zero Team USA (US)'],
    array['Arcade'],
    '{"mame":["zeroteam"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["seibu/raiden2.cpp"]}'::jsonb
  ),
  (
    'zero-wing',
    'Zero Wing',
    'Toaplan',
    1989,
    array['Zero Wing (2P set)'],
    array['Arcade'],
    '{"mame":["zerowing"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["toaplan/toaplan1.cpp"]}'::jsonb
  ),
  (
    'zero-zone',
    'Zero Zone',
    'Comad',
    1993,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zerozone"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["comad/zerozone.cpp"]}'::jsonb
  ),
  (
    'zeroize',
    'Zeroize',
    'Data East Corporation',
    1983,
    array['Zeroize (DECO Cassette) (US)'],
    array['Arcade'],
    '{"mame":["czeroize"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["dataeast/decocass.cpp"]}'::jsonb
  ),
  (
    'zexall-fpga-z80-test-interface',
    'Zexall (FPGA Z80 test interface)',
    'Frank Cringle / Kevin Horton',
    2009,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zexall"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["homebrew/zexall.cpp"]}'::jsonb
  ),
  (
    'zhongguo-chu-da-d-v102c',
    'Zhongguo Chu Da D (V102C)',
    'IGS',
    2000,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zhongguo"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["igs/igs_m027.cpp"]}'::jsonb
  ),
  (
    'zhongguo-long-pretty-chance-dragon-world-pretty-chance',
    'Zhongguo Long Pretty Chance [Dragon World Pretty Chance]',
    'IGS',
    2001,
    array['Zhongguo Long Pretty Chance [Dragon World Pretty Chance] (V110 03/19/02 11:13:16, China)'],
    array['Arcade'],
    '{"mame":["dwpc"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["igs/pgm.cpp"]}'::jsonb
  ),
  (
    'zhongji-dou-dizhu-v204cn',
    'Zhongji Dou Dizhu (V204CN)',
    'IGS',
    2010,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zjddz"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["igs/igs_m036.cpp"]}'::jsonb
  ),
  (
    'zig-zag',
    'Zig Zag',
    'bootleg (LAX)',
    1982,
    array['Zig Zag (bootleg Dig Dug conversion on Galaxian hardware, set 1)'],
    array['Arcade'],
    '{"mame":["zigzagb"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["galaxian/galaxian.cpp"]}'::jsonb
  ),
  (
    'zing-zing-zip-zhen-zhen-ji-pao',
    'Zing Zing Zip / Zhen Zhen Ji Pao',
    'Allumer / Tecmo',
    1992,
    array['Zing Zing Zip (World) / Zhen Zhen Ji Pao (China?)'],
    array['Arcade'],
    '{"mame":["zingzip"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["seta/seta.cpp"]}'::jsonb
  ),
  (
    'zintrick-oshidashi-zentrix',
    'Zintrick / Oshidashi Zentrix',
    'bootleg',
    1996,
    array['Zintrick / Oshidashi Zentrix (bootleg of CD version)'],
    array['Arcade'],
    '{"mame":["zintrckb"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["neogeo/neogeo.cpp"]}'::jsonb
  ),
  (
    'zip-and-zap-explicit',
    'Zip & Zap (Explicit)',
    'Barko Corp',
    1995,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zipzap"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["kaneko/expro02.cpp"]}'::jsonb
  ),
  (
    'zircon-ii',
    'Zircon II',
    'Novag Industries / Intelligent Heuristic Programming',
    1995,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zircon2"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["novag/zircon2.cpp"]}'::jsonb
  ),
  (
    'zl-383-400-in-1-handheld-console',
    'ZL-383 400-in-1 Handheld Console',
    '<unknown>',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zl383"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["nintendo/nes_vt369_vtunknown.cpp"]}'::jsonb
  ),
  (
    'zoar',
    'Zoar',
    'Data East USA',
    1982,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zoar"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["dataeast/btime.cpp"]}'::jsonb
  ),
  (
    'zodiack',
    'Zodiack',
    'Orca (Esco Trading Co., Inc. license)',
    1983,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zodiack"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["orca/zodiack.cpp"]}'::jsonb
  ),
  (
    'zoids-infinity',
    'Zoids Infinity',
    'Tomy / Taito',
    2004,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zoidsinf"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["namco/namcops2.cpp"]}'::jsonb
  ),
  (
    'zoids-infinity-ex-plus',
    'Zoids Infinity EX Plus',
    'Tomy / Taito',
    2006,
    array['Zoids Infinity EX Plus (ver. 2.10)'],
    array['Arcade'],
    '{"mame":["zoidiexp"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["namco/namcops2.cpp"]}'::jsonb
  ),
  (
    'zombie-raid',
    'Zombie Raid',
    'American Sammy',
    1995,
    array['Zombie Raid (9/28/95, US)'],
    array['Arcade'],
    '{"mame":["zombraid"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["seta/seta.cpp"]}'::jsonb
  ),
  (
    'zombie-revenge',
    'Zombie Revenge',
    'Sega',
    1999,
    array['Zombie Revenge (Rev A)'],
    array['Arcade'],
    '{"mame":["zombrvn"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/naomi.cpp"]}'::jsonb
  ),
  (
    'zone-7-in-1-sports-ntsc',
    'Zone 7-in-1 Sports (NTSC)',
    'Ultimate Products Ltd.',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zone7in1"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["nintendo/vt1682.cpp"]}'::jsonb
  ),
  (
    'zone-fusion',
    'Zone Fusion',
    'Ultimate Products / Jungle''s Soft',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zonefusn"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["nintendo/nes_vt369_vtunknown.cpp"]}'::jsonb
  ),
  (
    'zoo',
    'Zoo',
    'Astro Corp.',
    2004,
    array['Zoo (Ver. ZO.02.D, Aug 27 2004)'],
    array['Arcade'],
    '{"mame":["zoo"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["astrocorp/astrcorp.cpp"]}'::jsonb
  ),
  (
    'zoo-keeper',
    'Zoo Keeper',
    'Taito America Corporation',
    1982,
    array['Zoo Keeper (set 1)'],
    array['Arcade'],
    '{"mame":["zookeep"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["taito/qix.cpp"]}'::jsonb
  ),
  (
    'zoofari',
    'Zoofari',
    'ICE/Play Mechanix',
    2006,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zoofari"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["ice/vp101.cpp"]}'::jsonb
  ),
  (
    'zoomania',
    'Zoomania',
    'Industrias Brasileiras',
    null,
    array['Zoomania (Version 10.04, set 1)'],
    array['Arcade'],
    '{"mame":["zoomania"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/highvdeo.cpp"]}'::jsonb
  ),
  (
    'zoomer-z-pda-z-7000',
    'Zoomer (Z-PDA / Z-7000)',
    'Casio / Tandy',
    1993,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zoomer"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["casio/zoomer.cpp"]}'::jsonb
  ),
  (
    'zooty-drum',
    'Zooty Drum',
    'PARA Enterprises',
    2000,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zdrum"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/pasha2.cpp"]}'::jsonb
  ),
  (
    'zorton-brothers-los-justicieros-v1-01',
    'Zorton Brothers / Los Justicieros (v1.01)',
    'Picmatic',
    1994,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zortonbr"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["amiga/alg.cpp"]}'::jsonb
  ),
  (
    'zrt-80',
    'ZRT-80',
    'Digital Research Computers',
    1982,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zrt80"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["drc/zrt80.cpp"]}'::jsonb
  ),
  (
    'zsbc-3',
    'ZSBC-3',
    'Digital Microsystems',
    1980,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zsbc3"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["dms/zsbc3.cpp"]}'::jsonb
  ),
  (
    'zuanshi-wutai-v110ii',
    'Zuanshi Wutai (V110II)',
    'IGS',
    1996,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zuanshiw"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["igs/spoker.cpp"]}'::jsonb
  ),
  (
    'zudu-go-2udu-go',
    'Zudu-go / 2udu-go',
    'Macro Winners / Waixing',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zudugo"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["nintendo/nes_vt02_vt03.cpp"]}'::jsonb
  ),
  (
    'zun-zun-block',
    'Zun Zun Block',
    'Taito',
    1979,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zzblock"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["taito/taitottl.cpp"]}'::jsonb
  ),
  (
    'zunzunkyou-no-yabou',
    'Zunzunkyou no Yabou',
    'Sega',
    1994,
    array['Zunzunkyou no Yabou (Japan)'],
    array['Arcade'],
    '{"mame":["zunkyou"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["sega/segac2.cpp"]}'::jsonb
  ),
  (
    'zupapa-italian-gambling-game',
    'Zupapa (Italian gambling game)',
    '<unknown>',
    null,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zupapah8"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["misc/itgambl2.cpp"]}'::jsonb
  ),
  (
    'zupapa',
    'Zupapa!',
    'SNK',
    2001,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zupapa"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["neogeo/neogeo.cpp"]}'::jsonb
  ),
  (
    'zuqiu-wang-king-of-football',
    'Zuqiu Wang - King of Football',
    'BMC',
    1995,
    '{}'::text[],
    array['Sports'],
    '{"mame":["koftball"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["bmc/koftball.cpp"]}'::jsonb
  ),
  (
    'zwackery',
    'Zwackery',
    'Bally Midway',
    1984,
    '{}'::text[],
    array['Arcade'],
    '{"mame":["zwackery"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["midway/zwackery.cpp"]}'::jsonb
  ),
  (
    'zzyzzyxx',
    'Zzyzzyxx',
    'Cinematronics / Advanced Microcomputer Systems',
    1982,
    array['Zzyzzyxx (set 1)'],
    array['Arcade'],
    '{"mame":["zzyzzyxx"]}'::jsonb,
    '{"excluded_noise":["gambling","handheld","home-computer","home-console","pinball","plug-and-play"],"include_mechanical":false,"import_policy":"parents-only","source":"mame-listxml","source_file":"mame.xml","source_files":["cinematronics/jack.cpp"]}'::jsonb
  )
on conflict (slug) do update
set
  title = excluded.title,
  manufacturer = coalesce(g.manufacturer, excluded.manufacturer),
  release_year = coalesce(g.release_year, excluded.release_year),
  aliases = (
    select array(
      select distinct alias_value
      from unnest(coalesce(g.aliases, '{}'::text[]) || excluded.aliases) as merged_aliases(alias_value)
      where alias_value <> ''
      order by alias_value
    )
  ),
  categories = (
    select array(
      select distinct category_value
      from unnest(coalesce(g.categories, '{}'::text[]) || excluded.categories) as merged_categories(category_value)
      where category_value <> ''
      order by category_value
    )
  ),
  external_ids = jsonb_set(
    coalesce(g.external_ids, '{}'::jsonb) || (excluded.external_ids - 'mame'),
    '{mame}',
    (
      select to_jsonb(array(
        select distinct mame_id
        from jsonb_array_elements_text(coalesce(g.external_ids -> 'mame', '[]'::jsonb) || coalesce(excluded.external_ids -> 'mame', '[]'::jsonb)) as merged_mame_ids(mame_id)
        order by mame_id
      ))
    ),
    true
  ),
  metadata = coalesce(g.metadata, '{}'::jsonb) || excluded.metadata;

commit;
